#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DeliveriesApp.Droid.Resource", IsApplication=true)]

namespace DeliveriesApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::DeliveriesApp.Droid.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::DeliveriesApp.Droid.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::DeliveriesApp.Droid.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::DeliveriesApp.Droid.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::DeliveriesApp.Droid.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::DeliveriesApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::DeliveriesApp.Droid.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::DeliveriesApp.Droid.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::DeliveriesApp.Droid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::DeliveriesApp.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_in_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_out_left = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090008
			public const int SaveButton = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int confirmPasswordEditText = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int emailEditText = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int fragmentContainer = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int menu_add = 2131296273;
			
			// aapt resource value: 0x7f090007
			public const int packageNameEditText = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int passwordEditText = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int registerButton = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int registerEmailEditText = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int registerPasswordEditText = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int registerUserButton = 2131296269;
			
			// aapt resource value: 0x7f090005
			public const int signinButton = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int textView1 = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int textView2 = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int textView3 = 2131296258;
			
			// aapt resource value: 0x7f090010
			public const int toolbar = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int toolbar_bottom = 2131296271;
			
			// aapt resource value: 0x7f090000
			public const int webview = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_webview = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Delivered = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Deliveries = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int NewDelivery = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Profile = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Register = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Tabs = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int toolbar = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int tabsMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_create = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_content_redo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_action_content_save = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_action_content_undo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_action_social_share = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Icon = 2130903045;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int hello = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int title_activity_webview = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
